apiVersion: v1
kind: Pod
metadata:
  name: server-delivery-pod
  labels:
    name: server-delivery-pod
    app: ctse-delivery

spec:
  containers:
    - name: shop-delivery-pod
      image: nishanniriella/ctse-delivery
      ports:
        - containerPort: 8080