apiVersion: v1
kind: Service
metadata:
  name: server-delivery-pod
  labels:
    name: server-delivery-pod
    app: ctse-app

spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: server-delivery-pod
    app: ctse-app
© 2022 GitHub, Inc.
Terms
Privac